### ISSUE TITLE
The options 'driver' or 'driverClass' are mandatory if no PDO instance is given to 

### ISSUE THREAD

**Issue by georgringer** [ksjogo/platformsh-typo3-template#12]
Sadly I can't open the backend as there is a message
```
The options 'driver' or 'driverClass' are mandatory if no PDO instance is given to DriverManager::getConnection().
```

any ideas?

**Comment by ksjogo** [comment]
Thanks for the report Georg, I will look into it.

**Comment by ksjogo** [comment]
There seems to be a problem with the current typo3_console version, as it will not handle our LocalConfiguration.php symlink properly.

**Comment by ksjogo** [comment]
I forked again and updated our master, could you please retry?
