### ISSUE TITLE
MySQL Database Character

### ISSUE THREAD

**Issue by dkd-dobberkau** [ksjogo/platformsh-typo3-template#8]
In the reports module there is a warning on:
"MySQL Database Character Set 	Wrong value detected
Your default database uses character set "latin1", but only "utf8" or "utf8mb4" is supported with TYPO3."
Can you check if you can influence this?

**Comment by bmack** [comment]
Duplicate of https://github.com/platformsh/platformsh-example-typo3/issues/1

**Comment by ksjogo** [comment]
Closing here.
